name = "erdos684_lean"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Erdos684Lean", "Challenge", "Solution"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "PrimeNumberTheoremAnd"
git = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd"
rev = "a5154676af9aa3095150ee410cdda80555aa0642"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "905b95818eb32af7874a58b427f50c1711a5e96c"

[[lean_lib]]
name = "Erdos684Lean"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
